// +build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityObservation) DeepCopyInto(out *IdentityObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityObservation.
func (in *IdentityObservation) DeepCopy() *IdentityObservation {
	if in == nil {
		return nil
	}
	out := new(IdentityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityParameters) DeepCopyInto(out *IdentityParameters) {
	*out = *in
	if in.IdentityIds != nil {
		in, out := &in.IdentityIds, &out.IdentityIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityParameters.
func (in *IdentityParameters) DeepCopy() *IdentityParameters {
	if in == nil {
		return nil
	}
	out := new(IdentityParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAccountObservation) DeepCopyInto(out *StorageAccountObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAccountObservation.
func (in *StorageAccountObservation) DeepCopy() *StorageAccountObservation {
	if in == nil {
		return nil
	}
	out := new(StorageAccountObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageAccountParameters) DeepCopyInto(out *StorageAccountParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageAccountParameters.
func (in *StorageAccountParameters) DeepCopy() *StorageAccountParameters {
	if in == nil {
		return nil
	}
	out := new(StorageAccountParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoAnalyzer) DeepCopyInto(out *VideoAnalyzer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoAnalyzer.
func (in *VideoAnalyzer) DeepCopy() *VideoAnalyzer {
	if in == nil {
		return nil
	}
	out := new(VideoAnalyzer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VideoAnalyzer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoAnalyzerEdgeModule) DeepCopyInto(out *VideoAnalyzerEdgeModule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoAnalyzerEdgeModule.
func (in *VideoAnalyzerEdgeModule) DeepCopy() *VideoAnalyzerEdgeModule {
	if in == nil {
		return nil
	}
	out := new(VideoAnalyzerEdgeModule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VideoAnalyzerEdgeModule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoAnalyzerEdgeModuleList) DeepCopyInto(out *VideoAnalyzerEdgeModuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VideoAnalyzerEdgeModule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoAnalyzerEdgeModuleList.
func (in *VideoAnalyzerEdgeModuleList) DeepCopy() *VideoAnalyzerEdgeModuleList {
	if in == nil {
		return nil
	}
	out := new(VideoAnalyzerEdgeModuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VideoAnalyzerEdgeModuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoAnalyzerEdgeModuleObservation) DeepCopyInto(out *VideoAnalyzerEdgeModuleObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoAnalyzerEdgeModuleObservation.
func (in *VideoAnalyzerEdgeModuleObservation) DeepCopy() *VideoAnalyzerEdgeModuleObservation {
	if in == nil {
		return nil
	}
	out := new(VideoAnalyzerEdgeModuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoAnalyzerEdgeModuleParameters) DeepCopyInto(out *VideoAnalyzerEdgeModuleParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoAnalyzerEdgeModuleParameters.
func (in *VideoAnalyzerEdgeModuleParameters) DeepCopy() *VideoAnalyzerEdgeModuleParameters {
	if in == nil {
		return nil
	}
	out := new(VideoAnalyzerEdgeModuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoAnalyzerEdgeModuleSpec) DeepCopyInto(out *VideoAnalyzerEdgeModuleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoAnalyzerEdgeModuleSpec.
func (in *VideoAnalyzerEdgeModuleSpec) DeepCopy() *VideoAnalyzerEdgeModuleSpec {
	if in == nil {
		return nil
	}
	out := new(VideoAnalyzerEdgeModuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoAnalyzerEdgeModuleStatus) DeepCopyInto(out *VideoAnalyzerEdgeModuleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoAnalyzerEdgeModuleStatus.
func (in *VideoAnalyzerEdgeModuleStatus) DeepCopy() *VideoAnalyzerEdgeModuleStatus {
	if in == nil {
		return nil
	}
	out := new(VideoAnalyzerEdgeModuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoAnalyzerList) DeepCopyInto(out *VideoAnalyzerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VideoAnalyzer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoAnalyzerList.
func (in *VideoAnalyzerList) DeepCopy() *VideoAnalyzerList {
	if in == nil {
		return nil
	}
	out := new(VideoAnalyzerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VideoAnalyzerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoAnalyzerObservation) DeepCopyInto(out *VideoAnalyzerObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoAnalyzerObservation.
func (in *VideoAnalyzerObservation) DeepCopy() *VideoAnalyzerObservation {
	if in == nil {
		return nil
	}
	out := new(VideoAnalyzerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoAnalyzerParameters) DeepCopyInto(out *VideoAnalyzerParameters) {
	*out = *in
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = make([]IdentityParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StorageAccount != nil {
		in, out := &in.StorageAccount, &out.StorageAccount
		*out = make([]StorageAccountParameters, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoAnalyzerParameters.
func (in *VideoAnalyzerParameters) DeepCopy() *VideoAnalyzerParameters {
	if in == nil {
		return nil
	}
	out := new(VideoAnalyzerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoAnalyzerSpec) DeepCopyInto(out *VideoAnalyzerSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoAnalyzerSpec.
func (in *VideoAnalyzerSpec) DeepCopy() *VideoAnalyzerSpec {
	if in == nil {
		return nil
	}
	out := new(VideoAnalyzerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoAnalyzerStatus) DeepCopyInto(out *VideoAnalyzerStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoAnalyzerStatus.
func (in *VideoAnalyzerStatus) DeepCopy() *VideoAnalyzerStatus {
	if in == nil {
		return nil
	}
	out := new(VideoAnalyzerStatus)
	in.DeepCopyInto(out)
	return out
}
