// +build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionConfigurationObservation) DeepCopyInto(out *ConnectionConfigurationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionConfigurationObservation.
func (in *ConnectionConfigurationObservation) DeepCopy() *ConnectionConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(ConnectionConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionConfigurationParameters) DeepCopyInto(out *ConnectionConfigurationParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = make([]RouteParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VpnClientAddressPool != nil {
		in, out := &in.VpnClientAddressPool, &out.VpnClientAddressPool
		*out = make([]VpnClientAddressPoolParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionConfigurationParameters.
func (in *ConnectionConfigurationParameters) DeepCopy() *ConnectionConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(ConnectionConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropagatedRouteTableObservation) DeepCopyInto(out *PropagatedRouteTableObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropagatedRouteTableObservation.
func (in *PropagatedRouteTableObservation) DeepCopy() *PropagatedRouteTableObservation {
	if in == nil {
		return nil
	}
	out := new(PropagatedRouteTableObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropagatedRouteTableParameters) DeepCopyInto(out *PropagatedRouteTableParameters) {
	*out = *in
	if in.Ids != nil {
		in, out := &in.Ids, &out.Ids
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropagatedRouteTableParameters.
func (in *PropagatedRouteTableParameters) DeepCopy() *PropagatedRouteTableParameters {
	if in == nil {
		return nil
	}
	out := new(PropagatedRouteTableParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteObservation) DeepCopyInto(out *RouteObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteObservation.
func (in *RouteObservation) DeepCopy() *RouteObservation {
	if in == nil {
		return nil
	}
	out := new(RouteObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteParameters) DeepCopyInto(out *RouteParameters) {
	*out = *in
	if in.AssociatedRouteTableID != nil {
		in, out := &in.AssociatedRouteTableID, &out.AssociatedRouteTableID
		*out = new(string)
		**out = **in
	}
	if in.PropagatedRouteTable != nil {
		in, out := &in.PropagatedRouteTable, &out.PropagatedRouteTable
		*out = make([]PropagatedRouteTableParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteParameters.
func (in *RouteParameters) DeepCopy() *RouteParameters {
	if in == nil {
		return nil
	}
	out := new(RouteParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToSiteVpnGateway) DeepCopyInto(out *ToSiteVpnGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToSiteVpnGateway.
func (in *ToSiteVpnGateway) DeepCopy() *ToSiteVpnGateway {
	if in == nil {
		return nil
	}
	out := new(ToSiteVpnGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToSiteVpnGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToSiteVpnGatewayList) DeepCopyInto(out *ToSiteVpnGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ToSiteVpnGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToSiteVpnGatewayList.
func (in *ToSiteVpnGatewayList) DeepCopy() *ToSiteVpnGatewayList {
	if in == nil {
		return nil
	}
	out := new(ToSiteVpnGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToSiteVpnGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToSiteVpnGatewayObservation) DeepCopyInto(out *ToSiteVpnGatewayObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToSiteVpnGatewayObservation.
func (in *ToSiteVpnGatewayObservation) DeepCopy() *ToSiteVpnGatewayObservation {
	if in == nil {
		return nil
	}
	out := new(ToSiteVpnGatewayObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToSiteVpnGatewayParameters) DeepCopyInto(out *ToSiteVpnGatewayParameters) {
	*out = *in
	if in.ConnectionConfiguration != nil {
		in, out := &in.ConnectionConfiguration, &out.ConnectionConfiguration
		*out = make([]ConnectionConfigurationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DNSServers != nil {
		in, out := &in.DNSServers, &out.DNSServers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.ScaleUnit != nil {
		in, out := &in.ScaleUnit, &out.ScaleUnit
		*out = new(int64)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VirtualHubID != nil {
		in, out := &in.VirtualHubID, &out.VirtualHubID
		*out = new(string)
		**out = **in
	}
	if in.VpnServerConfigurationID != nil {
		in, out := &in.VpnServerConfigurationID, &out.VpnServerConfigurationID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToSiteVpnGatewayParameters.
func (in *ToSiteVpnGatewayParameters) DeepCopy() *ToSiteVpnGatewayParameters {
	if in == nil {
		return nil
	}
	out := new(ToSiteVpnGatewayParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToSiteVpnGatewaySpec) DeepCopyInto(out *ToSiteVpnGatewaySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToSiteVpnGatewaySpec.
func (in *ToSiteVpnGatewaySpec) DeepCopy() *ToSiteVpnGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(ToSiteVpnGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToSiteVpnGatewayStatus) DeepCopyInto(out *ToSiteVpnGatewayStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToSiteVpnGatewayStatus.
func (in *ToSiteVpnGatewayStatus) DeepCopy() *ToSiteVpnGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(ToSiteVpnGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpnClientAddressPoolObservation) DeepCopyInto(out *VpnClientAddressPoolObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpnClientAddressPoolObservation.
func (in *VpnClientAddressPoolObservation) DeepCopy() *VpnClientAddressPoolObservation {
	if in == nil {
		return nil
	}
	out := new(VpnClientAddressPoolObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpnClientAddressPoolParameters) DeepCopyInto(out *VpnClientAddressPoolParameters) {
	*out = *in
	if in.AddressPrefixes != nil {
		in, out := &in.AddressPrefixes, &out.AddressPrefixes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpnClientAddressPoolParameters.
func (in *VpnClientAddressPoolParameters) DeepCopy() *VpnClientAddressPoolParameters {
	if in == nil {
		return nil
	}
	out := new(VpnClientAddressPoolParameters)
	in.DeepCopyInto(out)
	return out
}
