/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AccessRuleObservation struct {
}

type AccessRuleParameters struct {

	// +kubebuilder:validation:Required
	Access *string `json:"access" tf:"access,omitempty"`

	// +kubebuilder:validation:Optional
	AnonymousGID *int64 `json:"anonymousGid,omitempty" tf:"anonymous_gid,omitempty"`

	// +kubebuilder:validation:Optional
	AnonymousUID *int64 `json:"anonymousUid,omitempty" tf:"anonymous_uid,omitempty"`

	// +kubebuilder:validation:Optional
	Filter *string `json:"filter,omitempty" tf:"filter,omitempty"`

	// +kubebuilder:validation:Optional
	RootSquashEnabled *bool `json:"rootSquashEnabled,omitempty" tf:"root_squash_enabled,omitempty"`

	// +kubebuilder:validation:Required
	Scope *string `json:"scope" tf:"scope,omitempty"`

	// +kubebuilder:validation:Optional
	SubmountAccessEnabled *bool `json:"submountAccessEnabled,omitempty" tf:"submount_access_enabled,omitempty"`

	// +kubebuilder:validation:Optional
	SuidEnabled *bool `json:"suidEnabled,omitempty" tf:"suid_enabled,omitempty"`
}

type BindObservation struct {
}

type BindParameters struct {

	// +kubebuilder:validation:Required
	Dn *string `json:"dn" tf:"dn,omitempty"`

	// +kubebuilder:validation:Required
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`
}

type CacheObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	MountAddresses []*string `json:"mountAddresses,omitempty" tf:"mount_addresses,omitempty"`
}

type CacheParameters struct {

	// +kubebuilder:validation:Required
	CacheSizeInGb *int64 `json:"cacheSizeInGb" tf:"cache_size_in_gb,omitempty"`

	// +kubebuilder:validation:Optional
	DNS []DNSParameters `json:"dns,omitempty" tf:"dns,omitempty"`

	// +kubebuilder:validation:Optional
	DefaultAccessPolicy []DefaultAccessPolicyParameters `json:"defaultAccessPolicy,omitempty" tf:"default_access_policy,omitempty"`

	// +kubebuilder:validation:Optional
	DirectoryActiveDirectory []DirectoryActiveDirectoryParameters `json:"directoryActiveDirectory,omitempty" tf:"directory_active_directory,omitempty"`

	// +kubebuilder:validation:Optional
	DirectoryFlatFile []DirectoryFlatFileParameters `json:"directoryFlatFile,omitempty" tf:"directory_flat_file,omitempty"`

	// +kubebuilder:validation:Optional
	DirectoryLdap []DirectoryLdapParameters `json:"directoryLdap,omitempty" tf:"directory_ldap,omitempty"`

	// +kubebuilder:validation:Required
	Location *string `json:"location" tf:"location,omitempty"`

	// +kubebuilder:validation:Optional
	Mtu *int64 `json:"mtu,omitempty" tf:"mtu,omitempty"`

	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	NtpServer *string `json:"ntpServer,omitempty" tf:"ntp_server,omitempty"`

	// +kubebuilder:validation:Required
	ResourceGroupName *string `json:"resourceGroupName" tf:"resource_group_name,omitempty"`

	// +kubebuilder:validation:Optional
	RootSquashEnabled *bool `json:"rootSquashEnabled,omitempty" tf:"root_squash_enabled,omitempty"`

	// +kubebuilder:validation:Required
	SkuName *string `json:"skuName" tf:"sku_name,omitempty"`

	// +kubebuilder:validation:Required
	SubnetID *string `json:"subnetId" tf:"subnet_id,omitempty"`

	// +kubebuilder:validation:Optional
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type DNSObservation struct {
}

type DNSParameters struct {

	// +kubebuilder:validation:Optional
	SearchDomain *string `json:"searchDomain,omitempty" tf:"search_domain,omitempty"`

	// +kubebuilder:validation:Required
	Servers []*string `json:"servers" tf:"servers,omitempty"`
}

type DefaultAccessPolicyObservation struct {
}

type DefaultAccessPolicyParameters struct {

	// +kubebuilder:validation:Required
	AccessRule []AccessRuleParameters `json:"accessRule" tf:"access_rule,omitempty"`
}

type DirectoryActiveDirectoryObservation struct {
}

type DirectoryActiveDirectoryParameters struct {

	// +kubebuilder:validation:Required
	CacheNetbiosName *string `json:"cacheNetbiosName" tf:"cache_netbios_name,omitempty"`

	// +kubebuilder:validation:Required
	DNSPrimaryIP *string `json:"dnsPrimaryIp" tf:"dns_primary_ip,omitempty"`

	// +kubebuilder:validation:Optional
	DNSSecondaryIP *string `json:"dnsSecondaryIp,omitempty" tf:"dns_secondary_ip,omitempty"`

	// +kubebuilder:validation:Required
	DomainName *string `json:"domainName" tf:"domain_name,omitempty"`

	// +kubebuilder:validation:Required
	DomainNetbiosName *string `json:"domainNetbiosName" tf:"domain_netbios_name,omitempty"`

	// +kubebuilder:validation:Required
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// +kubebuilder:validation:Required
	Username *string `json:"username" tf:"username,omitempty"`
}

type DirectoryFlatFileObservation struct {
}

type DirectoryFlatFileParameters struct {

	// +kubebuilder:validation:Required
	GroupFileURI *string `json:"groupFileUri" tf:"group_file_uri,omitempty"`

	// +kubebuilder:validation:Required
	PasswordFileURI *string `json:"passwordFileUri" tf:"password_file_uri,omitempty"`
}

type DirectoryLdapObservation struct {
}

type DirectoryLdapParameters struct {

	// +kubebuilder:validation:Required
	BaseDn *string `json:"baseDn" tf:"base_dn,omitempty"`

	// +kubebuilder:validation:Optional
	Bind []BindParameters `json:"bind,omitempty" tf:"bind,omitempty"`

	// +kubebuilder:validation:Optional
	CertificateValidationURI *string `json:"certificateValidationUri,omitempty" tf:"certificate_validation_uri,omitempty"`

	// +kubebuilder:validation:Optional
	DownloadCertificateAutomatically *bool `json:"downloadCertificateAutomatically,omitempty" tf:"download_certificate_automatically,omitempty"`

	// +kubebuilder:validation:Optional
	Encrypted *bool `json:"encrypted,omitempty" tf:"encrypted,omitempty"`

	// +kubebuilder:validation:Required
	Server *string `json:"server" tf:"server,omitempty"`
}

// CacheSpec defines the desired state of Cache
type CacheSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CacheParameters `json:"forProvider"`
}

// CacheStatus defines the observed state of Cache.
type CacheStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CacheObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Cache is the Schema for the Caches API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azurejet}
type Cache struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CacheSpec   `json:"spec"`
	Status            CacheStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CacheList contains a list of Caches
type CacheList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Cache `json:"items"`
}

// Repository type metadata.
var (
	Cache_Kind             = "Cache"
	Cache_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Cache_Kind}.String()
	Cache_KindAPIVersion   = Cache_Kind + "." + CRDGroupVersion.String()
	Cache_GroupVersionKind = CRDGroupVersion.WithKind(Cache_Kind)
)

func init() {
	SchemeBuilder.Register(&Cache{}, &CacheList{})
}
