/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

type DnsZoneObservation struct {
	MaxNumberOfRecordSets int64 `json:"maxNumberOfRecordSets" tf:"max_number_of_record_sets"`

	NameServers []string `json:"nameServers" tf:"name_servers"`

	NumberOfRecordSets int64 `json:"numberOfRecordSets" tf:"number_of_record_sets"`
}

type DnsZoneParameters struct {
	Name string `json:"name" tf:"name"`

	ResourceGroupName string `json:"resourceGroupName" tf:"resource_group_name"`

	SoaRecord []SoaRecordParameters `json:"soaRecord,omitempty" tf:"soa_record"`

	Tags map[string]string `json:"tags,omitempty" tf:"tags"`
}

type SoaRecordObservation struct {
	Fqdn string `json:"fqdn" tf:"fqdn"`
}

type SoaRecordParameters struct {
	Email string `json:"email" tf:"email"`

	ExpireTime *int64 `json:"expireTime,omitempty" tf:"expire_time"`

	HostName string `json:"hostName" tf:"host_name"`

	MinimumTTL *int64 `json:"minimumTtl,omitempty" tf:"minimum_ttl"`

	RefreshTime *int64 `json:"refreshTime,omitempty" tf:"refresh_time"`

	RetryTime *int64 `json:"retryTime,omitempty" tf:"retry_time"`

	SerialNumber *int64 `json:"serialNumber,omitempty" tf:"serial_number"`

	TTL *int64 `json:"ttl,omitempty" tf:"ttl"`

	Tags map[string]string `json:"tags,omitempty" tf:"tags"`
}

// DnsZoneSpec defines the desired state of DnsZone
type DnsZoneSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       DnsZoneParameters `json:"forProvider"`
}

// DnsZoneStatus defines the observed state of DnsZone.
type DnsZoneStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          DnsZoneObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// DnsZone is the Schema for the DnsZones API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azure}
type DnsZone struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DnsZoneSpec   `json:"spec"`
	Status            DnsZoneStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DnsZoneList contains a list of DnsZones
type DnsZoneList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DnsZone `json:"items"`
}

// Repository type metadata.
var (
	DnsZoneKind             = "DnsZone"
	DnsZoneGroupKind        = schema.GroupKind{Group: Group, Kind: DnsZoneKind}.String()
	DnsZoneKindAPIVersion   = DnsZoneKind + "." + GroupVersion.String()
	DnsZoneGroupVersionKind = GroupVersion.WithKind(DnsZoneKind)
)

func init() {
	SchemeBuilder.Register(&DnsZone{}, &DnsZoneList{})
}
