/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

type BotChannelDirectLineSpeechObservation struct {
}

type BotChannelDirectLineSpeechParameters struct {
	BotName string `json:"botName" tf:"bot_name"`

	CognitiveServiceAccessKey string `json:"cognitiveServiceAccessKey" tf:"cognitive_service_access_key"`

	CognitiveServiceLocation string `json:"cognitiveServiceLocation" tf:"cognitive_service_location"`

	CustomSpeechModelID *string `json:"customSpeechModelId,omitempty" tf:"custom_speech_model_id"`

	CustomVoiceDeploymentID *string `json:"customVoiceDeploymentId,omitempty" tf:"custom_voice_deployment_id"`

	Location string `json:"location" tf:"location"`

	ResourceGroupName string `json:"resourceGroupName" tf:"resource_group_name"`
}

// BotChannelDirectLineSpeechSpec defines the desired state of BotChannelDirectLineSpeech
type BotChannelDirectLineSpeechSpec struct {
	xpv1.ResourceSpec `json:",inline"`
	ForProvider       BotChannelDirectLineSpeechParameters `json:"forProvider"`
}

// BotChannelDirectLineSpeechStatus defines the observed state of BotChannelDirectLineSpeech.
type BotChannelDirectLineSpeechStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          BotChannelDirectLineSpeechObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// BotChannelDirectLineSpeech is the Schema for the BotChannelDirectLineSpeechs API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azure}
type BotChannelDirectLineSpeech struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BotChannelDirectLineSpeechSpec   `json:"spec"`
	Status            BotChannelDirectLineSpeechStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BotChannelDirectLineSpeechList contains a list of BotChannelDirectLineSpeechs
type BotChannelDirectLineSpeechList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BotChannelDirectLineSpeech `json:"items"`
}

// Repository type metadata.
var (
	BotChannelDirectLineSpeechKind             = "BotChannelDirectLineSpeech"
	BotChannelDirectLineSpeechGroupKind        = schema.GroupKind{Group: Group, Kind: BotChannelDirectLineSpeechKind}.String()
	BotChannelDirectLineSpeechKindAPIVersion   = BotChannelDirectLineSpeechKind + "." + GroupVersion.String()
	BotChannelDirectLineSpeechGroupVersionKind = GroupVersion.WithKind(BotChannelDirectLineSpeechKind)
)

func init() {
	SchemeBuilder.Register(&BotChannelDirectLineSpeech{}, &BotChannelDirectLineSpeechList{})
}
