// +build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowRuleObservation) DeepCopyInto(out *AllowRuleObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowRuleObservation.
func (in *AllowRuleObservation) DeepCopy() *AllowRuleObservation {
	if in == nil {
		return nil
	}
	out := new(AllowRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowRuleParameters) DeepCopyInto(out *AllowRuleParameters) {
	*out = *in
	if in.ConnectionToIPNotAllowed != nil {
		in, out := &in.ConnectionToIPNotAllowed, &out.ConnectionToIPNotAllowed
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LocalUserNotAllowed != nil {
		in, out := &in.LocalUserNotAllowed, &out.LocalUserNotAllowed
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ProcessNotAllowed != nil {
		in, out := &in.ProcessNotAllowed, &out.ProcessNotAllowed
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowRuleParameters.
func (in *AllowRuleParameters) DeepCopy() *AllowRuleParameters {
	if in == nil {
		return nil
	}
	out := new(AllowRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyPropertyObservation) DeepCopyInto(out *KeyPropertyObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyPropertyObservation.
func (in *KeyPropertyObservation) DeepCopy() *KeyPropertyObservation {
	if in == nil {
		return nil
	}
	out := new(KeyPropertyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyPropertyParameters) DeepCopyInto(out *KeyPropertyParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyPropertyParameters.
func (in *KeyPropertyParameters) DeepCopy() *KeyPropertyParameters {
	if in == nil {
		return nil
	}
	out := new(KeyPropertyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RangeRuleObservation) DeepCopyInto(out *RangeRuleObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RangeRuleObservation.
func (in *RangeRuleObservation) DeepCopy() *RangeRuleObservation {
	if in == nil {
		return nil
	}
	out := new(RangeRuleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RangeRuleParameters) DeepCopyInto(out *RangeRuleParameters) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int64)
		**out = **in
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RangeRuleParameters.
func (in *RangeRuleParameters) DeepCopy() *RangeRuleParameters {
	if in == nil {
		return nil
	}
	out := new(RangeRuleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendationsEnabledObservation) DeepCopyInto(out *RecommendationsEnabledObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendationsEnabledObservation.
func (in *RecommendationsEnabledObservation) DeepCopy() *RecommendationsEnabledObservation {
	if in == nil {
		return nil
	}
	out := new(RecommendationsEnabledObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendationsEnabledParameters) DeepCopyInto(out *RecommendationsEnabledParameters) {
	*out = *in
	if in.AcrAuthentication != nil {
		in, out := &in.AcrAuthentication, &out.AcrAuthentication
		*out = new(bool)
		**out = **in
	}
	if in.AgentSendUnutilizedMsg != nil {
		in, out := &in.AgentSendUnutilizedMsg, &out.AgentSendUnutilizedMsg
		*out = new(bool)
		**out = **in
	}
	if in.Baseline != nil {
		in, out := &in.Baseline, &out.Baseline
		*out = new(bool)
		**out = **in
	}
	if in.EdgeHubMemOptimize != nil {
		in, out := &in.EdgeHubMemOptimize, &out.EdgeHubMemOptimize
		*out = new(bool)
		**out = **in
	}
	if in.EdgeLoggingOption != nil {
		in, out := &in.EdgeLoggingOption, &out.EdgeLoggingOption
		*out = new(bool)
		**out = **in
	}
	if in.IPFilterDenyAll != nil {
		in, out := &in.IPFilterDenyAll, &out.IPFilterDenyAll
		*out = new(bool)
		**out = **in
	}
	if in.IPFilterPermissiveRule != nil {
		in, out := &in.IPFilterPermissiveRule, &out.IPFilterPermissiveRule
		*out = new(bool)
		**out = **in
	}
	if in.InconsistentModuleSettings != nil {
		in, out := &in.InconsistentModuleSettings, &out.InconsistentModuleSettings
		*out = new(bool)
		**out = **in
	}
	if in.InstallAgent != nil {
		in, out := &in.InstallAgent, &out.InstallAgent
		*out = new(bool)
		**out = **in
	}
	if in.OpenPorts != nil {
		in, out := &in.OpenPorts, &out.OpenPorts
		*out = new(bool)
		**out = **in
	}
	if in.PermissiveFirewallPolicy != nil {
		in, out := &in.PermissiveFirewallPolicy, &out.PermissiveFirewallPolicy
		*out = new(bool)
		**out = **in
	}
	if in.PermissiveInputFirewallRules != nil {
		in, out := &in.PermissiveInputFirewallRules, &out.PermissiveInputFirewallRules
		*out = new(bool)
		**out = **in
	}
	if in.PermissiveOutputFirewallRules != nil {
		in, out := &in.PermissiveOutputFirewallRules, &out.PermissiveOutputFirewallRules
		*out = new(bool)
		**out = **in
	}
	if in.PrivilegedDockerOptions != nil {
		in, out := &in.PrivilegedDockerOptions, &out.PrivilegedDockerOptions
		*out = new(bool)
		**out = **in
	}
	if in.SharedCredentials != nil {
		in, out := &in.SharedCredentials, &out.SharedCredentials
		*out = new(bool)
		**out = **in
	}
	if in.VulnerableTLSCipherSuite != nil {
		in, out := &in.VulnerableTLSCipherSuite, &out.VulnerableTLSCipherSuite
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendationsEnabledParameters.
func (in *RecommendationsEnabledParameters) DeepCopy() *RecommendationsEnabledParameters {
	if in == nil {
		return nil
	}
	out := new(RecommendationsEnabledParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityDeviceGroup) DeepCopyInto(out *SecurityDeviceGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityDeviceGroup.
func (in *SecurityDeviceGroup) DeepCopy() *SecurityDeviceGroup {
	if in == nil {
		return nil
	}
	out := new(SecurityDeviceGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityDeviceGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityDeviceGroupList) DeepCopyInto(out *SecurityDeviceGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityDeviceGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityDeviceGroupList.
func (in *SecurityDeviceGroupList) DeepCopy() *SecurityDeviceGroupList {
	if in == nil {
		return nil
	}
	out := new(SecurityDeviceGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityDeviceGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityDeviceGroupObservation) DeepCopyInto(out *SecurityDeviceGroupObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityDeviceGroupObservation.
func (in *SecurityDeviceGroupObservation) DeepCopy() *SecurityDeviceGroupObservation {
	if in == nil {
		return nil
	}
	out := new(SecurityDeviceGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityDeviceGroupParameters) DeepCopyInto(out *SecurityDeviceGroupParameters) {
	*out = *in
	if in.AllowRule != nil {
		in, out := &in.AllowRule, &out.AllowRule
		*out = make([]AllowRuleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IothubID != nil {
		in, out := &in.IothubID, &out.IothubID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RangeRule != nil {
		in, out := &in.RangeRule, &out.RangeRule
		*out = make([]RangeRuleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityDeviceGroupParameters.
func (in *SecurityDeviceGroupParameters) DeepCopy() *SecurityDeviceGroupParameters {
	if in == nil {
		return nil
	}
	out := new(SecurityDeviceGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityDeviceGroupSpec) DeepCopyInto(out *SecurityDeviceGroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityDeviceGroupSpec.
func (in *SecurityDeviceGroupSpec) DeepCopy() *SecurityDeviceGroupSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityDeviceGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityDeviceGroupStatus) DeepCopyInto(out *SecurityDeviceGroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityDeviceGroupStatus.
func (in *SecurityDeviceGroupStatus) DeepCopy() *SecurityDeviceGroupStatus {
	if in == nil {
		return nil
	}
	out := new(SecurityDeviceGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySolution) DeepCopyInto(out *SecuritySolution) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySolution.
func (in *SecuritySolution) DeepCopy() *SecuritySolution {
	if in == nil {
		return nil
	}
	out := new(SecuritySolution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecuritySolution) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySolutionList) DeepCopyInto(out *SecuritySolutionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecuritySolution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySolutionList.
func (in *SecuritySolutionList) DeepCopy() *SecuritySolutionList {
	if in == nil {
		return nil
	}
	out := new(SecuritySolutionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecuritySolutionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySolutionObservation) DeepCopyInto(out *SecuritySolutionObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySolutionObservation.
func (in *SecuritySolutionObservation) DeepCopy() *SecuritySolutionObservation {
	if in == nil {
		return nil
	}
	out := new(SecuritySolutionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySolutionParameters) DeepCopyInto(out *SecuritySolutionParameters) {
	*out = *in
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EventsToExport != nil {
		in, out := &in.EventsToExport, &out.EventsToExport
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IothubIds != nil {
		in, out := &in.IothubIds, &out.IothubIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.LogAnalyticsWorkspaceID != nil {
		in, out := &in.LogAnalyticsWorkspaceID, &out.LogAnalyticsWorkspaceID
		*out = new(string)
		**out = **in
	}
	if in.LogUnmaskedIpsEnabled != nil {
		in, out := &in.LogUnmaskedIpsEnabled, &out.LogUnmaskedIpsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.QueryForResources != nil {
		in, out := &in.QueryForResources, &out.QueryForResources
		*out = new(string)
		**out = **in
	}
	if in.QuerySubscriptionIds != nil {
		in, out := &in.QuerySubscriptionIds, &out.QuerySubscriptionIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RecommendationsEnabled != nil {
		in, out := &in.RecommendationsEnabled, &out.RecommendationsEnabled
		*out = make([]RecommendationsEnabledParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySolutionParameters.
func (in *SecuritySolutionParameters) DeepCopy() *SecuritySolutionParameters {
	if in == nil {
		return nil
	}
	out := new(SecuritySolutionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySolutionSpec) DeepCopyInto(out *SecuritySolutionSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySolutionSpec.
func (in *SecuritySolutionSpec) DeepCopy() *SecuritySolutionSpec {
	if in == nil {
		return nil
	}
	out := new(SecuritySolutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySolutionStatus) DeepCopyInto(out *SecuritySolutionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySolutionStatus.
func (in *SecuritySolutionStatus) DeepCopy() *SecuritySolutionStatus {
	if in == nil {
		return nil
	}
	out := new(SecuritySolutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageObservation) DeepCopyInto(out *StorageObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageObservation.
func (in *StorageObservation) DeepCopy() *StorageObservation {
	if in == nil {
		return nil
	}
	out := new(StorageObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageParameters) DeepCopyInto(out *StorageParameters) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageParameters.
func (in *StorageParameters) DeepCopy() *StorageParameters {
	if in == nil {
		return nil
	}
	out := new(StorageParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsAccessPolicy) DeepCopyInto(out *TimeSeriesInsightsAccessPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsAccessPolicy.
func (in *TimeSeriesInsightsAccessPolicy) DeepCopy() *TimeSeriesInsightsAccessPolicy {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsAccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimeSeriesInsightsAccessPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsAccessPolicyList) DeepCopyInto(out *TimeSeriesInsightsAccessPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TimeSeriesInsightsAccessPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsAccessPolicyList.
func (in *TimeSeriesInsightsAccessPolicyList) DeepCopy() *TimeSeriesInsightsAccessPolicyList {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsAccessPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimeSeriesInsightsAccessPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsAccessPolicyObservation) DeepCopyInto(out *TimeSeriesInsightsAccessPolicyObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsAccessPolicyObservation.
func (in *TimeSeriesInsightsAccessPolicyObservation) DeepCopy() *TimeSeriesInsightsAccessPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsAccessPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsAccessPolicyParameters) DeepCopyInto(out *TimeSeriesInsightsAccessPolicyParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PrincipalObjectID != nil {
		in, out := &in.PrincipalObjectID, &out.PrincipalObjectID
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TimeSeriesInsightsEnvironmentID != nil {
		in, out := &in.TimeSeriesInsightsEnvironmentID, &out.TimeSeriesInsightsEnvironmentID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsAccessPolicyParameters.
func (in *TimeSeriesInsightsAccessPolicyParameters) DeepCopy() *TimeSeriesInsightsAccessPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsAccessPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsAccessPolicySpec) DeepCopyInto(out *TimeSeriesInsightsAccessPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsAccessPolicySpec.
func (in *TimeSeriesInsightsAccessPolicySpec) DeepCopy() *TimeSeriesInsightsAccessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsAccessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsAccessPolicyStatus) DeepCopyInto(out *TimeSeriesInsightsAccessPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsAccessPolicyStatus.
func (in *TimeSeriesInsightsAccessPolicyStatus) DeepCopy() *TimeSeriesInsightsAccessPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsAccessPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsEventSourceIothub) DeepCopyInto(out *TimeSeriesInsightsEventSourceIothub) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsEventSourceIothub.
func (in *TimeSeriesInsightsEventSourceIothub) DeepCopy() *TimeSeriesInsightsEventSourceIothub {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsEventSourceIothub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimeSeriesInsightsEventSourceIothub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsEventSourceIothubList) DeepCopyInto(out *TimeSeriesInsightsEventSourceIothubList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TimeSeriesInsightsEventSourceIothub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsEventSourceIothubList.
func (in *TimeSeriesInsightsEventSourceIothubList) DeepCopy() *TimeSeriesInsightsEventSourceIothubList {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsEventSourceIothubList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimeSeriesInsightsEventSourceIothubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsEventSourceIothubObservation) DeepCopyInto(out *TimeSeriesInsightsEventSourceIothubObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsEventSourceIothubObservation.
func (in *TimeSeriesInsightsEventSourceIothubObservation) DeepCopy() *TimeSeriesInsightsEventSourceIothubObservation {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsEventSourceIothubObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsEventSourceIothubParameters) DeepCopyInto(out *TimeSeriesInsightsEventSourceIothubParameters) {
	*out = *in
	if in.ConsumerGroupName != nil {
		in, out := &in.ConsumerGroupName, &out.ConsumerGroupName
		*out = new(string)
		**out = **in
	}
	if in.EnvironmentID != nil {
		in, out := &in.EnvironmentID, &out.EnvironmentID
		*out = new(string)
		**out = **in
	}
	if in.EventSourceResourceID != nil {
		in, out := &in.EventSourceResourceID, &out.EventSourceResourceID
		*out = new(string)
		**out = **in
	}
	if in.IothubName != nil {
		in, out := &in.IothubName, &out.IothubName
		*out = new(string)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SharedAccessKey != nil {
		in, out := &in.SharedAccessKey, &out.SharedAccessKey
		*out = new(string)
		**out = **in
	}
	if in.SharedAccessKeyName != nil {
		in, out := &in.SharedAccessKeyName, &out.SharedAccessKeyName
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TimestampPropertyName != nil {
		in, out := &in.TimestampPropertyName, &out.TimestampPropertyName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsEventSourceIothubParameters.
func (in *TimeSeriesInsightsEventSourceIothubParameters) DeepCopy() *TimeSeriesInsightsEventSourceIothubParameters {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsEventSourceIothubParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsEventSourceIothubSpec) DeepCopyInto(out *TimeSeriesInsightsEventSourceIothubSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsEventSourceIothubSpec.
func (in *TimeSeriesInsightsEventSourceIothubSpec) DeepCopy() *TimeSeriesInsightsEventSourceIothubSpec {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsEventSourceIothubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsEventSourceIothubStatus) DeepCopyInto(out *TimeSeriesInsightsEventSourceIothubStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsEventSourceIothubStatus.
func (in *TimeSeriesInsightsEventSourceIothubStatus) DeepCopy() *TimeSeriesInsightsEventSourceIothubStatus {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsEventSourceIothubStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsGen2Environment) DeepCopyInto(out *TimeSeriesInsightsGen2Environment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsGen2Environment.
func (in *TimeSeriesInsightsGen2Environment) DeepCopy() *TimeSeriesInsightsGen2Environment {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsGen2Environment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimeSeriesInsightsGen2Environment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsGen2EnvironmentList) DeepCopyInto(out *TimeSeriesInsightsGen2EnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TimeSeriesInsightsGen2Environment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsGen2EnvironmentList.
func (in *TimeSeriesInsightsGen2EnvironmentList) DeepCopy() *TimeSeriesInsightsGen2EnvironmentList {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsGen2EnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimeSeriesInsightsGen2EnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsGen2EnvironmentObservation) DeepCopyInto(out *TimeSeriesInsightsGen2EnvironmentObservation) {
	*out = *in
	if in.DataAccessFqdn != nil {
		in, out := &in.DataAccessFqdn, &out.DataAccessFqdn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsGen2EnvironmentObservation.
func (in *TimeSeriesInsightsGen2EnvironmentObservation) DeepCopy() *TimeSeriesInsightsGen2EnvironmentObservation {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsGen2EnvironmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsGen2EnvironmentParameters) DeepCopyInto(out *TimeSeriesInsightsGen2EnvironmentParameters) {
	*out = *in
	if in.IDProperties != nil {
		in, out := &in.IDProperties, &out.IDProperties
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.SkuName != nil {
		in, out := &in.SkuName, &out.SkuName
		*out = new(string)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = make([]StorageParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.WarmStoreDataRetentionTime != nil {
		in, out := &in.WarmStoreDataRetentionTime, &out.WarmStoreDataRetentionTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsGen2EnvironmentParameters.
func (in *TimeSeriesInsightsGen2EnvironmentParameters) DeepCopy() *TimeSeriesInsightsGen2EnvironmentParameters {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsGen2EnvironmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsGen2EnvironmentSpec) DeepCopyInto(out *TimeSeriesInsightsGen2EnvironmentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsGen2EnvironmentSpec.
func (in *TimeSeriesInsightsGen2EnvironmentSpec) DeepCopy() *TimeSeriesInsightsGen2EnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsGen2EnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsGen2EnvironmentStatus) DeepCopyInto(out *TimeSeriesInsightsGen2EnvironmentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsGen2EnvironmentStatus.
func (in *TimeSeriesInsightsGen2EnvironmentStatus) DeepCopy() *TimeSeriesInsightsGen2EnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsGen2EnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsReferenceDataSet) DeepCopyInto(out *TimeSeriesInsightsReferenceDataSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsReferenceDataSet.
func (in *TimeSeriesInsightsReferenceDataSet) DeepCopy() *TimeSeriesInsightsReferenceDataSet {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsReferenceDataSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimeSeriesInsightsReferenceDataSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsReferenceDataSetList) DeepCopyInto(out *TimeSeriesInsightsReferenceDataSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TimeSeriesInsightsReferenceDataSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsReferenceDataSetList.
func (in *TimeSeriesInsightsReferenceDataSetList) DeepCopy() *TimeSeriesInsightsReferenceDataSetList {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsReferenceDataSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimeSeriesInsightsReferenceDataSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsReferenceDataSetObservation) DeepCopyInto(out *TimeSeriesInsightsReferenceDataSetObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsReferenceDataSetObservation.
func (in *TimeSeriesInsightsReferenceDataSetObservation) DeepCopy() *TimeSeriesInsightsReferenceDataSetObservation {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsReferenceDataSetObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsReferenceDataSetParameters) DeepCopyInto(out *TimeSeriesInsightsReferenceDataSetParameters) {
	*out = *in
	if in.DataStringComparisonBehavior != nil {
		in, out := &in.DataStringComparisonBehavior, &out.DataStringComparisonBehavior
		*out = new(string)
		**out = **in
	}
	if in.KeyProperty != nil {
		in, out := &in.KeyProperty, &out.KeyProperty
		*out = make([]KeyPropertyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TimeSeriesInsightsEnvironmentID != nil {
		in, out := &in.TimeSeriesInsightsEnvironmentID, &out.TimeSeriesInsightsEnvironmentID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsReferenceDataSetParameters.
func (in *TimeSeriesInsightsReferenceDataSetParameters) DeepCopy() *TimeSeriesInsightsReferenceDataSetParameters {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsReferenceDataSetParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsReferenceDataSetSpec) DeepCopyInto(out *TimeSeriesInsightsReferenceDataSetSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsReferenceDataSetSpec.
func (in *TimeSeriesInsightsReferenceDataSetSpec) DeepCopy() *TimeSeriesInsightsReferenceDataSetSpec {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsReferenceDataSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsReferenceDataSetStatus) DeepCopyInto(out *TimeSeriesInsightsReferenceDataSetStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsReferenceDataSetStatus.
func (in *TimeSeriesInsightsReferenceDataSetStatus) DeepCopy() *TimeSeriesInsightsReferenceDataSetStatus {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsReferenceDataSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsStandardEnvironment) DeepCopyInto(out *TimeSeriesInsightsStandardEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsStandardEnvironment.
func (in *TimeSeriesInsightsStandardEnvironment) DeepCopy() *TimeSeriesInsightsStandardEnvironment {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsStandardEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimeSeriesInsightsStandardEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsStandardEnvironmentList) DeepCopyInto(out *TimeSeriesInsightsStandardEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TimeSeriesInsightsStandardEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsStandardEnvironmentList.
func (in *TimeSeriesInsightsStandardEnvironmentList) DeepCopy() *TimeSeriesInsightsStandardEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsStandardEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TimeSeriesInsightsStandardEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsStandardEnvironmentObservation) DeepCopyInto(out *TimeSeriesInsightsStandardEnvironmentObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsStandardEnvironmentObservation.
func (in *TimeSeriesInsightsStandardEnvironmentObservation) DeepCopy() *TimeSeriesInsightsStandardEnvironmentObservation {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsStandardEnvironmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsStandardEnvironmentParameters) DeepCopyInto(out *TimeSeriesInsightsStandardEnvironmentParameters) {
	*out = *in
	if in.DataRetentionTime != nil {
		in, out := &in.DataRetentionTime, &out.DataRetentionTime
		*out = new(string)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PartitionKey != nil {
		in, out := &in.PartitionKey, &out.PartitionKey
		*out = new(string)
		**out = **in
	}
	if in.ResourceGroupName != nil {
		in, out := &in.ResourceGroupName, &out.ResourceGroupName
		*out = new(string)
		**out = **in
	}
	if in.SkuName != nil {
		in, out := &in.SkuName, &out.SkuName
		*out = new(string)
		**out = **in
	}
	if in.StorageLimitExceededBehavior != nil {
		in, out := &in.StorageLimitExceededBehavior, &out.StorageLimitExceededBehavior
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsStandardEnvironmentParameters.
func (in *TimeSeriesInsightsStandardEnvironmentParameters) DeepCopy() *TimeSeriesInsightsStandardEnvironmentParameters {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsStandardEnvironmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsStandardEnvironmentSpec) DeepCopyInto(out *TimeSeriesInsightsStandardEnvironmentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsStandardEnvironmentSpec.
func (in *TimeSeriesInsightsStandardEnvironmentSpec) DeepCopy() *TimeSeriesInsightsStandardEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsStandardEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSeriesInsightsStandardEnvironmentStatus) DeepCopyInto(out *TimeSeriesInsightsStandardEnvironmentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSeriesInsightsStandardEnvironmentStatus.
func (in *TimeSeriesInsightsStandardEnvironmentStatus) DeepCopy() *TimeSeriesInsightsStandardEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(TimeSeriesInsightsStandardEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}
