/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AzureBlobFsLocationObservation struct {
}

type AzureBlobFsLocationParameters struct {

	// +kubebuilder:validation:Required
	FileSystem *string `json:"fileSystem" tf:"file_system,omitempty"`

	// +kubebuilder:validation:Optional
	Filename *string `json:"filename,omitempty" tf:"filename,omitempty"`

	// +kubebuilder:validation:Optional
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type FactoryDatasetDelimitedTextAzureBlobStorageLocationObservation struct {
}

type FactoryDatasetDelimitedTextAzureBlobStorageLocationParameters struct {

	// +kubebuilder:validation:Required
	Container *string `json:"container" tf:"container,omitempty"`

	// +kubebuilder:validation:Optional
	DynamicFilenameEnabled *bool `json:"dynamicFilenameEnabled,omitempty" tf:"dynamic_filename_enabled,omitempty"`

	// +kubebuilder:validation:Optional
	DynamicPathEnabled *bool `json:"dynamicPathEnabled,omitempty" tf:"dynamic_path_enabled,omitempty"`

	// +kubebuilder:validation:Optional
	Filename *string `json:"filename,omitempty" tf:"filename,omitempty"`

	// +kubebuilder:validation:Optional
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type FactoryDatasetDelimitedTextHTTPServerLocationObservation struct {
}

type FactoryDatasetDelimitedTextHTTPServerLocationParameters struct {

	// +kubebuilder:validation:Optional
	DynamicFilenameEnabled *bool `json:"dynamicFilenameEnabled,omitempty" tf:"dynamic_filename_enabled,omitempty"`

	// +kubebuilder:validation:Optional
	DynamicPathEnabled *bool `json:"dynamicPathEnabled,omitempty" tf:"dynamic_path_enabled,omitempty"`

	// +kubebuilder:validation:Required
	Filename *string `json:"filename" tf:"filename,omitempty"`

	// +kubebuilder:validation:Required
	Path *string `json:"path" tf:"path,omitempty"`

	// +kubebuilder:validation:Required
	RelativeURL *string `json:"relativeUrl" tf:"relative_url,omitempty"`
}

type FactoryDatasetDelimitedTextObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type FactoryDatasetDelimitedTextParameters struct {

	// +kubebuilder:validation:Optional
	AdditionalProperties map[string]*string `json:"additionalProperties,omitempty" tf:"additional_properties,omitempty"`

	// +kubebuilder:validation:Optional
	Annotations []*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// +kubebuilder:validation:Optional
	AzureBlobFsLocation []AzureBlobFsLocationParameters `json:"azureBlobFsLocation,omitempty" tf:"azure_blob_fs_location,omitempty"`

	// +kubebuilder:validation:Optional
	AzureBlobStorageLocation []FactoryDatasetDelimitedTextAzureBlobStorageLocationParameters `json:"azureBlobStorageLocation,omitempty" tf:"azure_blob_storage_location,omitempty"`

	// +kubebuilder:validation:Optional
	ColumnDelimiter *string `json:"columnDelimiter,omitempty" tf:"column_delimiter,omitempty"`

	// +kubebuilder:validation:Optional
	CompressionCodec *string `json:"compressionCodec,omitempty" tf:"compression_codec,omitempty"`

	// +kubebuilder:validation:Optional
	CompressionLevel *string `json:"compressionLevel,omitempty" tf:"compression_level,omitempty"`

	// +kubebuilder:validation:Required
	DataFactoryName *string `json:"dataFactoryName" tf:"data_factory_name,omitempty"`

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	Encoding *string `json:"encoding,omitempty" tf:"encoding,omitempty"`

	// +kubebuilder:validation:Optional
	EscapeCharacter *string `json:"escapeCharacter,omitempty" tf:"escape_character,omitempty"`

	// +kubebuilder:validation:Optional
	FirstRowAsHeader *bool `json:"firstRowAsHeader,omitempty" tf:"first_row_as_header,omitempty"`

	// +kubebuilder:validation:Optional
	Folder *string `json:"folder,omitempty" tf:"folder,omitempty"`

	// +kubebuilder:validation:Optional
	HTTPServerLocation []FactoryDatasetDelimitedTextHTTPServerLocationParameters `json:"httpServerLocation,omitempty" tf:"http_server_location,omitempty"`

	// +kubebuilder:validation:Required
	LinkedServiceName *string `json:"linkedServiceName" tf:"linked_service_name,omitempty"`

	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	NullValue *string `json:"nullValue,omitempty" tf:"null_value,omitempty"`

	// +kubebuilder:validation:Optional
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// +kubebuilder:validation:Optional
	QuoteCharacter *string `json:"quoteCharacter,omitempty" tf:"quote_character,omitempty"`

	// +kubebuilder:validation:Required
	ResourceGroupName *string `json:"resourceGroupName" tf:"resource_group_name,omitempty"`

	// +kubebuilder:validation:Optional
	RowDelimiter *string `json:"rowDelimiter,omitempty" tf:"row_delimiter,omitempty"`

	// +kubebuilder:validation:Optional
	SchemaColumn []FactoryDatasetDelimitedTextSchemaColumnParameters `json:"schemaColumn,omitempty" tf:"schema_column,omitempty"`
}

type FactoryDatasetDelimitedTextSchemaColumnObservation struct {
}

type FactoryDatasetDelimitedTextSchemaColumnParameters struct {

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// FactoryDatasetDelimitedTextSpec defines the desired state of FactoryDatasetDelimitedText
type FactoryDatasetDelimitedTextSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FactoryDatasetDelimitedTextParameters `json:"forProvider"`
}

// FactoryDatasetDelimitedTextStatus defines the observed state of FactoryDatasetDelimitedText.
type FactoryDatasetDelimitedTextStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FactoryDatasetDelimitedTextObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// FactoryDatasetDelimitedText is the Schema for the FactoryDatasetDelimitedTexts API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,azurejet}
type FactoryDatasetDelimitedText struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FactoryDatasetDelimitedTextSpec   `json:"spec"`
	Status            FactoryDatasetDelimitedTextStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FactoryDatasetDelimitedTextList contains a list of FactoryDatasetDelimitedTexts
type FactoryDatasetDelimitedTextList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FactoryDatasetDelimitedText `json:"items"`
}

// Repository type metadata.
var (
	FactoryDatasetDelimitedText_Kind             = "FactoryDatasetDelimitedText"
	FactoryDatasetDelimitedText_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FactoryDatasetDelimitedText_Kind}.String()
	FactoryDatasetDelimitedText_KindAPIVersion   = FactoryDatasetDelimitedText_Kind + "." + CRDGroupVersion.String()
	FactoryDatasetDelimitedText_GroupVersionKind = CRDGroupVersion.WithKind(FactoryDatasetDelimitedText_Kind)
)

func init() {
	SchemeBuilder.Register(&FactoryDatasetDelimitedText{}, &FactoryDatasetDelimitedTextList{})
}
